---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos
    image: milcom/centos7-systemd
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible
  options:
   v: 1
